name: dartest
description: A simple command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.14.3 <3.0.0'


dependencies:
#   path: ^1.8.0
  dio: ^4.0.0
  charset: ^0.1.1

dev_dependencies:
  lints: ^1.0.0
