name: dartest
description: A simple command-line application.
version: 2.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.14.3 <3.0.0'


dependencies:
#   path: ^1.8.0
  args: ^2.3.0
  dio: ^4.0.0
  dio_cookie_manager: ^2.0.0
  cookie_jar: 3.0.1
  charset: ^0.2.2

dev_dependencies:
  lints: ^1.0.0
